command:
  - "python"
  - "app.py"

env:
  - name: DATABRICKS_WAREHOUSE_ID
    valueFrom: sql-warehouse

  - name: SERVING_ENDPOINT_NAME
    valueFrom: serving-endpoint

  - name: GENIE_SPACE_ID
    valueFrom: genie-space

  - name: SCHEMA
    value: "gabriel_rangel"

  - name: DASHBOARD_EMBED_URL
    value: "https://adb-7405608274245049.9.azuredatabricks.net/embed/dashboardsv3/01f13907caaf17f9aa3828dcfc8145b1"
