command:
  - "bash"
  - "-c"
  - "streamlit run app.py --server.port ${DATABRICKS_APP_PORT:-8000} --server.address 0.0.0.0 --server.headless true"

env:
  - name: DATABRICKS_WAREHOUSE_ID
    valueFrom: sql-warehouse

  - name: SERVING_ENDPOINT_NAME
    valueFrom: serving-endpoint

  - name: GENIE_SPACE_ID
    valueFrom: genie-space

  - name: DASHBOARD_EMBED_URL
    value: ""
